### ISSUE TITLE
Get It Working: Makefile

### ISSUE THREAD

**Issue by ldo** [larsbrinkhoff/smoking-clover#1]
I tried building it, and hit some errors.

First of all, I wasn’t sure if you were using GTK 2 or GTK 3, so I assumed GTK 2 to be safe. The referenced `gtk-config` tool doesn’t seem to exist, but I was able to fix the `Makefile` as follows:

    diff --git a/Makefile b/Makefile
    index 11c5bd3..7fb795a 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -1,7 +1,7 @@
    -CFLAGS = -g -Wall `gtk-config --cflags`
    -LIBS = `gtk-config --libs`
    +CFLAGS = -g -Wall `pkg-config --cflags gtk+-2.0`
    +LIBS = `pkg-config --libs gtk+-2.0` -lm

    -SRCS = README COPYING ChangeLog BUGS Makefile *.[ch] 
    +SRCS = README COPYING ChangeLog BUGS Makefile *.[ch]

     CLOVER_OBJS = clover.o common.o direct.o true.o rgb.o
     clover: $(CLOVER_OBJS)

**Comment by larsbrinkhoff** [comment]
Thanks for the patches!  I'll get them merged soon.
